
/*

,m
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.edu.facitec.tp.view;

import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import py.edu.facitec.tp.controller.CiudadController;
import py.edu.facitec.tp.controller.CiudadControllerImp;
import py.edu.facitec.tp.controller.ClienteController;
import py.edu.facitec.tp.controller.ClienteControllerImp;
import py.edu.facitec.tp.model.Cliente;

/**
 *
 * @author brother
 */
public class FormClienteBusqueda extends javax.swing.JFrame {

    /**
     * Creates new form FormClienteBusqueda
     */
    ClienteController clienteController;
    CiudadController ciudadController;
    public FormClienteBusqueda() {
        initComponents();
        this.clienteController = new ClienteControllerImp();
        this.ciudadController = new CiudadControllerImp();
        seleccionarBoton();
        DefaultComboBoxModel city = new DefaultComboBoxModel(ciudadController.cargarCombo());
        this.selectCiudad.setModel(city);
        estadoInicial();
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNOmbre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtCredito = new javax.swing.JTextField();
        btnEstado = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBusquedaId = new javax.swing.JRadioButton();
        btnBusquedaParametro = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        selectCiudad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SFNS Display", 0, 18)); // NOI18N
        jLabel1.setText("Consulta de Clientes");

        jLabel2.setText("Codigo:");

        jLabel3.setText("Nombre(s):");

        jLabel4.setText("Apellido(s):");

        jLabel5.setText("Direccion:");

        jLabel6.setText("Ciudad:");

        jLabel7.setText("Celular:");

        jLabel8.setText("Credito:");

        jLabel9.setText("Estado:");

        txtApellidos.setText(" ");

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        btnEstado.setText("Activo");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");

        BtnCancelar.setText("Cancelar");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("Modificar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBusquedaId.setText("Busqueda Por ID");
        btnBusquedaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaIdActionPerformed(evt);
            }
        });

        btnBusquedaParametro.setText("Busqueda Por Parametros");
        btnBusquedaParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaParametroActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SFNS Display", 0, 13)); // NOI18N
        jLabel10.setText("Seleccione opcion de Busqueda: ");

        selectCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBusquedaId)
                            .addComponent(jLabel10)
                            .addComponent(btnBusquedaParametro)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNOmbre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidos)
                                    .addComponent(txtDireccion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnEstado))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtCelular)
                                    .addComponent(selectCiudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBusquedaId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBusquedaParametro)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNOmbre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(selectCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(txtCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (btnBusquedaId.isSelected()) {
             consultarClientePorCodigo(Integer.parseInt(txtCodigo.getText()));
        }else{
            busquedaParametros();
        }
       
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBusquedaParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaParametroActionPerformed
        // TODO add your handling code here:
        btnBuscar.setEnabled(true);
        estadoParametro();
        
    }//GEN-LAST:event_btnBusquedaParametroActionPerformed

    private void btnBusquedaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaIdActionPerformed
        // TODO add your handling code here:
       btnBuscar.setEnabled(true);
        estadoID();
        
    }//GEN-LAST:event_btnBusquedaIdActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        cambiarCliente();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
        habilitarCampos();
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClienteBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClienteBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClienteBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClienteBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormClienteBusqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JRadioButton btnBusquedaId;
    private javax.swing.JRadioButton btnBusquedaParametro;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JCheckBox btnEstado;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> selectCiudad;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCredito;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNOmbre;
    // End of variables declaration//GEN-END:variables

    private void consultarClientePorCodigo(int codigo) {
        
        btnGuardar.setEnabled(true);
        BtnCancelar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnEditar.setEnabled(true);
        
        if (codigo != 0) {
            
            Cliente cliente = clienteController.buscarClientePorCodigo(codigo);
            
            if (cliente != null) {
                txtNOmbre.setText(cliente.getNombres());
                txtApellidos.setText(cliente.getApellidos());
                txtDireccion.setText(cliente.getDireccion());
                //txtCiudad.setText(cliente.getCiudad());
                selectCiudad.setSelectedIndex(cliente.getCiudad_codigo()-1);
                txtCelular.setText(cliente.getCelular());
                txtCredito.setText(cliente.getCredito()+"");
                btnEstado.setSelected(cliente.isEstado());

            }else{
            JOptionPane.showMessageDialog(this, "No existe cliente con este codigo, reintente");
            txtCodigo.setText("");
            
                        
            
            }
        }else{
            JOptionPane.showMessageDialog(this, "Este campo solo admite numeros, reintente");
            txtCodigo.setText("");
        }
    }

    private void desabilitarCamposBusqueda() {
       txtNOmbre.setEnabled(false);
       txtApellidos.setEnabled(false);
       txtDireccion.setEnabled(false);
       //txtCiudad.setEnabled(false);
       txtCelular.setEnabled(false);
       txtCredito.setEnabled(false);
      
       
    }

    private void estadoInicial() {
        
       txtNOmbre.setEnabled(false);
       txtApellidos.setEnabled(false);
       txtDireccion.setEnabled(false);
       //txtCiudad.setEnabled(false);
       txtCelular.setEnabled(false);
       txtCredito.setEnabled(false);
       btnGuardar.setEnabled(false);
       selectCiudad.setEnabled(false);
       BtnCancelar.setEnabled(false);
       btnEliminar.setEnabled(false);
       btnEstado.setEnabled(false);
       txtCodigo.setEnabled(false);
       btnEditar.setEnabled(false);
       btnBuscar.setEnabled(false);
        
    }
    public void estadoID(){
       txtCodigo.setEnabled(true);
       txtNOmbre.setEnabled(false);
       txtApellidos.setEnabled(false);
       txtDireccion.setEnabled(false);
    
       txtCelular.setEnabled(false);
       txtCredito.setEnabled(false);
       btnGuardar.setEnabled(false);
      
        BtnCancelar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnEstado.setEnabled(false);
         btnGuardar.setEnabled(false);
       btnEditar.setEnabled(false);
        
       
      
        
    }
   public void seleccionarBoton(){
       
       ButtonGroup group = new ButtonGroup();
       group.add(btnBusquedaId);
       group.add(btnBusquedaParametro);
       
      
       
           
       }

    private void estadoParametro() {
       txtNOmbre.setEnabled(true);
       txtApellidos.setEnabled(true);
       txtDireccion.setEnabled(true);
       txtCodigo.setEnabled(false);
       
       txtCelular.setEnabled(false);
       txtCredito.setEnabled(false);
       btnGuardar.setEnabled(false);
       btnEditar.setEnabled(false);
       
       
    }

    private void cambiarCliente() {
       
//        Cliente cliente = new Cliente(Integer.parseInt(txtCodigo.getText()), txtNOmbre.getText(), txtApellidos.getText(), txtDireccion.getText(), 
////                txtCelular.getText(), Double.parseDouble(txtCredito.getText()), btnEstado.isSelected());
           Cliente cliente = new Cliente();
           cliente.setCodigo(Integer.parseInt(txtCodigo.getText()));
           cliente.setNombres(txtNOmbre.getText());
           cliente.setApellidos(txtApellidos.getText());
           cliente.setDireccion(txtDireccion.getText());
           cliente.setCiudad_codigo(selectCiudad.getSelectedIndex()+1);
           cliente.setCelular(txtCelular.getText());
           cliente.setCredito(Double.parseDouble(txtCredito.getText()));
           cliente.setEstado(btnEstado.isSelected());
        
        boolean result = clienteController.modificarCliente(cliente);
        
            if(result){
             JOptionPane.showMessageDialog(this, "Cliente modificado con exito", "Aviso", 1);
         
        }
            limpiarCampos();
        
    }

    private void limpiarCampos() {
       txtNOmbre.setText("");
       txtApellidos.setText("");
       txtCelular.setText("");
       //txtCiudad.setText("");
       txtCodigo.setText("");
       txtCredito.setText("");
       btnEstado.setSelected(false);
       txtDireccion.setText("");
    }
    
    private void habilitarCampos(){
       txtNOmbre.setEnabled(true);
       txtApellidos.setEnabled(true);
       txtDireccion.setEnabled(true);
       txtCodigo.setEnabled(false);
       
       txtCelular.setEnabled(true);
       txtCredito.setEnabled(true);
       selectCiudad.setEnabled(true);
       btnEditar.setEnabled(true);
       
    }

    private void busquedaParametros() {
        clienteController.busquedaPorParametros(filtro);
    }
   }
        
